# Generated by Django 5.0.2 on 2024-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
